### ISSUE TITLE
support html selector in addition to :root

### ISSUE THREAD

**Issue by halmos** [postcss/postcss-custom-properties#100]
We're currently running up against a bug with latest MS Edge in that when printing, variables declared in `:root` are no properly handled (bot the variables and fallbacks are ignored. See: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/16025710/). Using `html`, however, does work. Since `:root` and `html` are more-or-less synonymous, would it possible for this plugin to also support variable declarations in `html`?

**Comment by jonathantneal** [comment]
That sounds totally reasonable to me.

**Comment by jagreehal** [comment]
Should this be configurable so a user can expand what is supported with the default being root? For web components, I need :host to also be supported.

**Comment by jonathantneal** [comment]
@jagreehal, that gets tricky, because then we’d be determining scope.
