### ISSUE TITLE
Feature request: add support for `noValueNotifications: 'off'`

### ISSUE THREAD

**Issue by mgcrea** [postcss/postcss-custom-properties#104]
Would be great to be able to pass `"off"` to the `noValueNotifications` option in addition to `"warning"` and `"error"` (just like eslint rules) to be able to selectively turn off these notifications without having to disable all warnings.

Will gladly submit a PR if you agree on the idea.

Thanks for the great work,

**Comment by jonathantneal** [comment]
Yes, I would accept a PR, especially if you show prior art for the option name/value.

**Comment by jonathantneal** [comment]
> When warnings are enabled, the noValueNotifications option 

Are you sure this doesn’t already do what you want?
