### ISSUE TITLE
External variable

### ISSUE THREAD

**Issue by augusto-jm-amaral** [postcss/postcss-custom-properties#105]
I import variables dynamically on the page, that is why I don't declare in css files, have some way to declare a var with external, preventing alerts from her?

**Comment by jonathantneal** [comment]
Yes, https://github.com/postcss/postcss-custom-properties#variables

**Comment by augusto-jm-amaral** [comment]
I'm Sorry @jonathantneal but I think I was not clear, this variable is dynamic, added at runtime, I can't add in `variables` because this will override all the places where I added the variables.

I didn't find a way, I disable warnings for now but I think the ideal would be to say that variable is global.
