### ISSUE TITLE
How do I import variables from npm package?

### ISSUE THREAD

**Issue by pavelozavr** [postcss/postcss-custom-properties#108]
Hi, I have an installed npm package with some variables, and I wanna use them inside my application. The plugin always crashes with the var is undefined error.

`//npm package file with vars`

`
:root {
  --default-font: Verdana;
}
`

Tryina import this file with `postcss-import ` plugin

`@import('@username/themes')`

It works, no errors about import or something

Tryina use the vars inside a css selector

`
.className {
  font-family: var(--default-font);
}
`

Getting  `default-font is undefined`

**Comment by jonathantneal** [comment]
This sounds like a plugin order. Could you provide a reduced test case, so that we can be sure or look into this further? Happy to help.
