### ISSUE TITLE
Suppress warnings 'Custom property ignored: not scoped to the top-level :root element'

### ISSUE THREAD

**Issue by tsesaihung** [postcss/postcss-custom-properties#117]
Are there any ways to use Angular Cli to suppress the warning of 'Custom property ignored: not scoped to the top-level :root element'?

This is the issue previously raised but no solutions were provided.

https://github.com/angular/angular-cli/issues/7991

**Comment by jonathantneal** [comment]
For now, the best way to do this is to use the `warnings` option.

https://github.com/postcss/postcss-custom-properties#warnings

**Comment by failpunk** [comment]
The warnings option has been removed. Now what?

**Comment by jonathantneal** [comment]
It no longer throws this warning.
