### ISSUE TITLE
Add warning when a custom prop is used in another place that :root ?

### ISSUE THREAD

**Issue by MoOx** [postcss/postcss-custom-properties#13]
I'm guessing this make sense according to the limitation.
This should create warning for all non root :root usage (in mq or in other selector)

**Comment by kevinSuttle** [comment]
Is there a way to silence these warnings at dev time? I have a situation where the warnings are present, but inaccurate (seemingly too early or too late), but the correct styles are applied. https://github.com/pascalduez/postcss-apply/issues/11#issuecomment-248404763

**Comment by MoOx** [comment]
Silence is not smart. The problem must be identified and fixed.

**Comment by kevinSuttle** [comment]
Screenshot: 
<img width="1436" alt="screen shot 2016-09-20 at 4 31 00 pm" src="https://cloud.githubusercontent.com/assets/95672/18687815/c20ea320-7f4f-11e6-9b54-4733ea7b09b4.png">

**Comment by kevinSuttle** [comment]
@MoOx This is at least part of the problem for me: https://github.com/webpack/webpack/issues/215
