### ISSUE TITLE
Move postcss to peerDependencies

### ISSUE THREAD

**Issue by stalniy** [postcss/postcss-custom-properties#130]
`postcss-custom-properties` is a plugin for `postcss` thus should include `postcss` as `peerDependency` and not as `depedency` in package.json. This basically allows to use whatever supported version of postcss together with the plugin and be sure that different postcss plugins use the same instance of postcss.

Please read this article https://nodejs.org/en/blog/npm/peer-dependencies/ for more details. 
I can create a PR if you are ok

**Comment by jonathantneal** [comment]
This will be resolved in https://github.com/csstools/postcss-preset-env/issues/65

And it doesn’t look like we will move the dependencies to peerDependecies. Something like greenkeeper is needed for all of these repositories.

**Comment by stalniy** [comment]
Please check this thread as well https://github.com/zgreen/postcss-critical-css/issues/28#issuecomment-414336983

I think still think dependency management of post css related libraries goes the wrong way and there are some proofs of that.

**Comment by stalniy** [comment]
Please read here https://lexi-lambda.github.io/blog/2016/08/24/understanding-the-npm-dependency-model/ for details
