### ISSUE TITLE
Add importFrom JSON example to README

### ISSUE THREAD

**Issue by ai** [postcss/postcss-custom-properties#136]
Like this https://github.com/postcss/postcss-custom-properties/blob/master/test/import-properties.json

**Comment by jonathantneal** [comment]
I’ve updated comment examples in the README, and I’ve also added links to the examples from the repository. How do you feel about these?

https://github.com/postcss/postcss-custom-properties/blob/release/8.0.1/README.md#importfrom

https://github.com/postcss/postcss-custom-properties/blob/release/8.0.1/README.md#exportto

**Comment by ai** [comment]
:+1:
