### ISSUE TITLE
preserve: false dosen't work

### ISSUE THREAD

**Issue by pldg** [postcss/postcss-custom-properties#138]
CSS variable are preserved even if `preserve: false`. This happen only for variables imported from another folder. A minimal test repository (with two temporary solutions): [test-postcss-custom-properties](https://github.com/pldg/test-postcss-custom-properties)

**Comment by jonathantneal** [comment]
The issue is that you are transforming the file without access to the variable, so it’s like you never imported another file at all. Unresolved custom properties are always preserved.

**Comment by pldg** [comment]
I'm not sure I understand.

I've two variables in **style.css**

- `--text-color` is from [style.css](https://github.com/pldg/test-postcss-custom-properties/blob/master/src/css/style.css) itself
- `--bg-color` is imported from another file inside another folder: [partials/var.css](https://github.com/pldg/test-postcss-custom-properties/blob/master/src/css/partials/var.css). 

Both variables are used inside `body` selector.

For what I understand `preserve: false` should transform both variables to their original value but as you can see in the bundle [dist/main.css](https://github.com/pldg/test-postcss-custom-properties/blob/master/dist/main.css) only `--text-color` is transformed to `red`. Why `--bg-color` is not transformed to `lightblue`?

**Comment by jonathantneal** [comment]
> --bg-color is imported from another file inside another folder: partials/var.css.

It is never imported at the time postcss runs. I don’t know why. That is why the property using `var()` is neither transformed or removed.

**Comment by pldg** [comment]
It's strange. Do you think it's a `postcss-loader`'s bug?

**Comment by jonathantneal** [comment]
Yes, or some kind of Webpack plugin ordering issue.
