### ISSUE TITLE
[Almost] Duplicated props from :root

### ISSUE THREAD

**Issue by joelmoss** [postcss/postcss-custom-properties#140]
So when I define a custom property within `:root`, the output duplicates the rules...

```
// input...
:root {
  --button-color: #000;
}
button {
    color: var(--button-color);
}

// output...
button {
    color: #8a8a8a;
    color: var(--button-color);
}
```

But if I move the properties to `body` or some other element, all is good.

Is this intentional?

**Comment by jonathantneal** [comment]
That is very curious. Can you spin up an example project that demonstrates this? Unless `preserve` is set to `false`, nothing should be removed.

**Comment by joelmoss** [comment]
So the output above is correct?

**Comment by jonathantneal** [comment]
No, which is why I need an example project to replicate the bug. Otherwise, it may remain inactive.

**Comment by jonathantneal** [comment]
I tested the following code at https://postcss.github.io/postcss-custom-properties/ and these were the results:

**source**:
```pcss
:root {
  --button-color: #000;
}

button {
    color: var(--button-color);
}
```

**result**:
```pcss
:root {
  --button-color: #000;
}

button {
    color: #000;
    color: var(--button-color);
}
```

**Comment by joelmoss** [comment]
Yes, so that result is wrong, right?

**Comment by joelmoss** [comment]
Ah ok, so what is that needed to be preserved?

**Comment by jonathantneal** [comment]
@joelmoss, that result is right, and @b-m-f is correct. I was concerned when your output did not include `:root {}`, but it looks like you were sharing only a snippet of your output. @b-m-f also points out the way to change this, if you don’t want to preserve the original variables.

**Comment by joelmoss** [comment]
Thanks. Why would I need to preserve it tho?
