### ISSUE TITLE
Var in string not working since 8.0.0

### ISSUE THREAD

**Issue by redaxmedia** [postcss/postcss-custom-properties#154]
This code use to work in 7.0.0

```
--rs-image-teaser: 974;

--rs-url-teaser-small: url('https://cdn.domain.com/unsplash/var(--rs-image-teaser)/small.jpg');
--rs-url-teaser-medium: url('https://cdn.domain.com/unsplash/var(--rs-image-teaser)/medium.jpg');
--rs-url-teaser-large: url('https://cdn.domain.com/unsplash/var(--rs-image-teaser)/large.jpg');
```

But since 8.0.0 it does not transform `var(--rs-image-teaser)` inside the url strings.

**Comment by jonathantneal** [comment]
While that’s cool it ever worked to begin with, that probably should not have worked worked before.

**Comment by redaxmedia** [comment]
Hehe, well... I used this to generate responsive image urls where the filename is usually equal but the rest like resolution suffix or extension are not.

This is quite handy. But if the official specs say something else - it is fine not to have this.

**Comment by redaxmedia** [comment]
I close this issue because I think this is not part of the official specs.
