### ISSUE TITLE
Custom properties cannot be accessed in custom property declaration  

### ISSUE THREAD

**Issue by lauriii** [postcss/postcss-custom-properties#174]
According to [W3C reference](https://www.w3.org/TR/css-variables-1/#cycles), custom properties should be able to depend on another variable. This is not currently supported by this library.

Example:
```
:root {
  --color: black;
}
div {
 --div-color: var(--color);
 color: var(--div-color);
}
```

Expected
```
div {
  color: black;
}
```

Current behavior:
```
div {
  color: ;
}
```

[I also created a failing test case for this.](https://github.com/lauriii/postcss-custom-properties/tree/test/referencing-custom-properties-from-custom-property)

**Comment by pascalduez** [comment]
Same as in https://github.com/postcss/postcss-custom-properties/issues/173#issuecomment-483530357
