### ISSUE TITLE
Combined selector with :root

### ISSUE THREAD

**Issue by ryuran** [postcss/postcss-custom-properties#198]
Hello !

I have an issue with a combined css selector

## Input CSS:
```
:root,
[data-theme=light] {
  --color-red: #A00;
}
body {
  color: var(--color-red);
}
```
## Expected output with `preserve: true`:
```
:root,
[data-theme=light] {
  --color-red: #A00;
}
body {
  color: #A00;
  color: var(--color-red);
}
```
## Expected output with `preserve: false`:
```
body {
  color: #A00;
}
```

**Comment by jonathantneal** [comment]
Great catch. My expectations would be slightly different:

## Expected output with `preserve: false`:
```
:root,
[data-theme=light] {
  --color-red: #A00;
}
body {
  color: #A00;
}
```

I would expect only pure `:root` or `html` custom properties would be removed, and only then would the rule be checked for emptiness before being discarded.

**Comment by ryuran** [comment]
I use `preserve: false` for replace every css custom properties by values.
Combined with postcss-filter-rules to remove rules related to `data-theme`.
So your expectation is OK for me to.

Which way should we take ?
