### ISSUE TITLE
Automatically add -- for JS injected vars

### ISSUE THREAD

**Issue by MoOx** [postcss/postcss-custom-properties#20]
`--` is a CSS thing.
Having to use that in the options is kind of weird.
We should prepend -- automatically if not present already.

poke @bloodyowl.

**Comment by bloodyowl** [comment]
big +1 on this, do you want me to PR?

— mlb

**Comment by MoOx** [comment]
Please have fun ;)

**Comment by MoOx** [comment]
Closed by 0691784ed2218d7e6b16da8c4df03e2ca0c4798c
