### ISSUE TITLE
Import from .pcss files

### ISSUE THREAD

**Issue by Charlie91** [postcss/postcss-custom-properties#209]
Hi.
I'm trying to get variables declared in specific file from any other `.pcss` file.

I'm doing it this way:
`        require('postcss-custom-properties')({
            preserve: false,
            importFrom: 'src/styles/base.css',
        }),
`
The problem is it is working only if I use css-file for my variables, and if I use it like this `importFrom: 'src/styles/base.pcss` it is not

**Comment by Semigradsky** [comment]
Fixed in https://github.com/postcss/postcss-custom-properties/releases/tag/9.2.0
