### ISSUE TITLE
Does this plugin strictly process variables that are only on :root?

### ISSUE THREAD

**Issue by cerino-ligutom** [postcss/postcss-custom-properties#213]
I see that this has been asked 4 years ago from #59 . Is this still the case? If yes, maybe it'd be better to put a note in the readme that that's strictly the case.

**Comment by pascalduez** [comment]
Hi @cerino-ligutom,

yes it's still the case. See https://github.com/postcss/postcss-custom-properties/issues/173#issuecomment-483530357

So basically a dupe of #173

**Comment by cerino-ligutom** [comment]
You'd probably want to put that detail on the readme. Been scratching my head over this for hours as I was expecting it to work just like in scss. Anyways, thanks for confirming quickly.

**Comment by pascalduez** [comment]
> You'd probably want to put that detail on the readme 

Agree, that's what I explain in that linked comment.   
I'm not a maintainer here.    
Maybe you could open a PR to add it back?

**Comment by cerino-ligutom** [comment]
Will try, might save others some time as well.

**Comment by zachleat** [comment]
:+1: this would be helpful as a README warning

**Comment by cerino-ligutom** [comment]
> 👍 this would be helpful as a README warning

Need that #214 bumped.
