### ISSUE TITLE
Force transformation and dont preserve?

### ISSUE THREAD

**Issue by badtant** [postcss/postcss-custom-properties#227]
Hi,

I'm using postcss-custom-properties via postcss-preset-env.
According to my browserlist setup it's safe to keep the custom properties and no transformation is needed.

Is there some way I can force a transformation anyway and not preserve?

Thanks

**Comment by Semigradsky** [comment]
@badtant You can disable specific feature: https://github.com/csstools/postcss-preset-env#features

**Comment by Semigradsky** [comment]
But `postcss-preset-env` should automatically disable features based on `browserlist` config. It can be bug in `postcss-preset-env`.
