### ISSUE TITLE
Resolve variables in media queries

### ISSUE THREAD

**Issue by hgl** [postcss/postcss-custom-properties#24]
As mentioned in https://gist.github.com/hgl/77f0141eea04817ee0af

I would like to make this plugin also resolve variables used in media queries (including custom media queries).

But I need your opinion on the breaking change to the `preserve` property I proposed in that gist (tl;dr enabling it doesn't fallback to specified values for resolvable values).

**Comment by MoOx** [comment]
This is invalid according to custom props specs so I won't add that into this module. I will close this issue when I will add a note about that in the Readme.

**Comment by hgl** [comment]
Is it because media queries don't inherit from the :root element?

**Comment by MoOx** [comment]
Yep.

**Comment by WolfgangKluge** [comment]
OK, here is a workaround.
https://github.com/WolfgangKluge/postcss-media-variables

**Comment by MoOx** [comment]
You should use [postcss-custom-media](https://github.com/postcss/postcss-custom-media/) instead to stay in the future of CSS.

**Comment by QuantumInformation** [comment]
I'm so happy about this!

**Comment by joshwcorbett** [comment]
> You should use [postcss-custom-media](https://github.com/postcss/postcss-custom-media/) instead to stay in the future of CSS.

It's 2021 now, and this plugin hasn't been updated in 4 years and doesn't support PostCSS 7 or newer. Has anyone found a workaround or just decided to downgrade to PostCSS 6?

**Comment by quantuminformation** [comment]
i feel old

**Comment by Spone** [comment]
> > You should use [postcss-custom-media](https://github.com/postcss/postcss-custom-media/) instead to stay in the future of CSS.
> 
> It's 2021 now, and this plugin hasn't been updated in 4 years and doesn't support PostCSS 7 or newer. Has anyone found a workaround or just decided to downgrade to PostCSS 6?

[v8.0.0](https://github.com/postcss/postcss-custom-media/releases/tag/8.0.0) supports PostCSS 8
