### ISSUE TITLE
 Error: Error: PostCSS plugin postcss-custom-properties requires PostCSS 8.

### ISSUE THREAD

**Issue by gitbu** [postcss/postcss-custom-properties#246]
Syntax Error: Error: PostCSS plugin postcss-custom-properties requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users

**Comment by noahtallen** [comment]
You likely need to update your PostCSS version to PostCSS 8 :)
