### ISSUE TITLE
Consider merging strict, preserve and appendVariables option as `strict`

### ISSUE THREAD

**Issue by MoOx** [postcss/postcss-custom-properties#26]
I think we can simplify the usage of those 3 options as one: strict.

strict set to true will
- add all fallbacks according to the specs
- preserve original author code as future proof code
- append user variables at the end to reflect make sense with previous points.
in order to be more close to specs

strict will be default to false in order to reduce output (and because I am sure some will whine :p)

poke watchers + @simonsmith @hgl what do you think about that ?

**Comment by hgl** [comment]
> - preserve original author code as future proof code
- append user variables at the end

Doing these two will make the custom properties harder to be extracted, for we have to remove author code when collecting computed values.

What about merging strict, appendVariables, preserve, but add `fallback: false` to remove fallbacks and author code?

**Comment by MoOx** [comment]
I didn't think about your issue indeed.
Maybe we can just merge appendVariables with preserve ?

**Comment by MoOx** [comment]
What about having only strict: bool || "computed"
false: reduced output to the minimum (default)
true: all the fucking possible output (computed + fallbacks)

Passing a variables object might affect strict: true to behave like "computed". Or we can just accept "computed" in strict option to behave like preserve: computed + appendVariables.

I am thinking about that to add a strict option to cssnext to enable/disable reduced output or output closer to the spec.

**Comment by hgl** [comment]
strict: "computed" sounds awkward.

preserve: false -> minimum
"all" -> computed + fallbacks
"computed" -> computed

What about this?

> I am thinking about that to add a strict option to cssnext

Good idea, i mentioned a similar `unsafe` option in #14. (IMO, cssnext should default to strict, better safe than sorry).

**Comment by hgl** [comment]
Maybe also a preserve: "specified"

```css

:root {
  --color: #aaa;
  --color2: #aaa;
}
body {
  color: #aaa;
  color: var(--color);
}
```

Basically, non-false `preserve` preserves the definitions.

**Comment by MoOx** [comment]
I think I will transform preserve the only option available with the following possibilities

- false (only new computed values (default))
- fallback: fallback (strict behavior) + previous
- true || all: specified + previous
- "computed-definition": current computed behavior (your hack to be able to extract). Renamed to be clear about what it keep. This option is weird anyway.

appendVariables will be automatic if you use a truthy preserve.

**Comment by hgl** [comment]
The current computed behavior also removes specified values in rules. So "computed-definition" not only affects definitions.

**Comment by MoOx** [comment]
Yeah but it preserve computed definition only, right ? So preserve: computed-definition seems clear to me.

**Comment by hgl** [comment]
What about turning preserve into an array? 

```js
false // only computed value, no definitions
[ // preserve definitions and
  "fallback", // strict behavior
  "specified", // specified value
]
```

So the current computed behavior is to pass an empty array.

**Comment by hgl** [comment]
The array can also be a space separated string.

**Comment by MoOx** [comment]
I though about that but found an issue with this method. I would like a simple "true" value that enable maximal safe output.

**Comment by MoOx** [comment]
If you think about it you will find an issue with the array thing

false: minimal
true: maximal
array ["specified", "fallback", "computed-definition"]

computed-definition overlap specified since specified are after computed-definition. So passing an array looks weird to me. + An empty array has never been a good solution. We need a verbose option name.

That why I came up with the 4 values false | true | fallback | computed.

**Comment by hgl** [comment]
With multiple parts being able to be preserve, a simple `preserve: true` feel ambiguous. `preserveAll: true` sounds more reasonable.

So what about we ditching `true`, but use "all" instead.

```js
false // only computed value, no definitions
[ // preserve definitions and
  "fallback", // strict behavior
  "specified", // specified value
]
"all" // maximum output
```

Passing `true` is undocumented thus undefined.

**Comment by hgl** [comment]
All we special case `true`, and treat it the same as "all"

**Comment by MoOx** [comment]
An empty array to enable a behavior looks like bad design to me :/

**Comment by hgl** [comment]
So what about a subtraction option

preserve:  true | false (max or min output)
exclude: ["fallback", "specified"]

**Comment by MoOx** [comment]
an option that depend on another is weird. What about this
preserve: bool (min,max)
preserve: {specified: bool, fallback: bool, whatever we can add: bool }
?

**Comment by hgl** [comment]
This means empty object enables a behavior.

**Comment by hgl** [comment]
an option that depends on another is pretty common. You see "only works under option x" fairly often in man pages.

**Comment by MoOx** [comment]
> This means empty object enables a behavior.
{} !== true
We can handle that. If a user pass an empty object he is clearly trying something :D

I like this quote
"Simplicity is the ultimate sophistication" - Leonardo Da Vinci.

So I am always trying to find the ultimate simple thing I can offer to people :)

If I quickly read the doc, I won't understand why there is an "exclude" option.

**Comment by hgl** [comment]
> So I am always trying to find the ultimate simple thing I can offer to people

I deeply respect that.

> If a user pass an empty object he is clearly trying something

The object option approach means this: passing an object option means enabling a major option but tuning sub-options, and passing an empty object means turning all sub-options off, but leave the major option enabled.

I feel enabling the major option and tuning sub-options should be in separate options. But I can live with the previous premise.

**Comment by MoOx** [comment]
We can consider an empty object is just like false ? Well this case, object can be an array indeed if it's just to enable some part.

With a second pass, my brain seems to accept this proposal as a simple one

preserve: bool (min,max)
preserve: [ // preserve definitions and
  "fallback", // + strict behavior
  "specified", // + specified value
]

because I think not that much people will use the empty array scenario. But the doc will need to be clear about that case.

**Comment by hgl** [comment]
What if we just do this:

preserve: {
  definition: bool // keep definition
  fallback: bool // keep fallback
  specified: bool // keep specified
}

Then we can treat an empty object the same as false.

**Comment by hgl** [comment]
preserve: true enables all four.

**Comment by hgl** [comment]
```
preserve: {
  definition: true,
  variables: false
}
```

means append variables, but not keep definition specified directly in css.

Maybe we are giving too much customization this way?

**Comment by MoOx** [comment]
We should just think about the possible scenario

- I want minimal output (false)
- I want safe output (+fallback)
- I want future proof code (+specified)
Edge case: I only want computed definition (not sure how to place this case in the list above :D)

**Comment by hgl** [comment]
I now think your four values for preserve is pretty good.

Only that I think "computed-definition" should just be "computed":

```css
:root {
	--color: #aaa;
	--color2: var(--color);
}

body {
	color: var(--color);
}
```

preserve: true

```css
:root {
	--color: #aaa;
	--color2: #aaa;
	--color2: var(--color);
}

body {
	color: #aaa;
	color: var(--color);
}
```

preserve: "computed-definition"

```css
:root {
	--color: #aaa;
	--color2: #aaa;
}

body {
	color: #aaa;
}
```

It also removes specified value in rules, not only in definitions.

**Comment by hgl** [comment]
And internally, we map the four values for preserve to bools for these variables

```
definition
fallback
specified
variables
```

So the code should be easier to read, and future values won't mess with the existing code.

**Comment by MoOx** [comment]
Not sure the predefined value make sense, but I agree with the four values. Will try to handle that tomorrow + release 4.0 :)

**Comment by MoOx** [comment]
After some dev on that I came up with

preserve: true || {specified, fallback}
preserveDefinition

preserve variables only doesn't make sense because you end up with a file that might not contains original specified values, but only one :root{} at the end. It's just weird.

and `preserve: definitions` was just conflicting `specified` everywhere, so since it's an edge case, I prefer to keep that as a separate option that overlap `preserve.specified`. This will need to be clear in the README that preserveDefinition will make preserve.specified ignored.

**Comment by hgl** [comment]
> but only one :root{} at the end. It's just weird.

Do you mean this is weird?

```css
body {
  color: #aaa;
}
:root {
  --js-defined: "no one uses this"
}
```

It's not weird. The custom properties in :root can be queried in supporting browsers. 
```js
document.documentElement.style.getPropertyValue("--js-defined"); // "no one uses this"
```
So leaving them there has a use case (at least in supporting browsers).

**Comment by MoOx** [comment]
No I mean

```css
:root {--a:b}
body{}
```
with variables and preserve.variables will give you

```css
body{}
:root{--js:*}
```
Which is weird because it seems you lost a part.
So I think you should better use just `preserveComputedDefinitions` (better than `preserveDefinitions` ?) which will preserve js (computed) variables as well.

**Comment by MoOx** [comment]
variables + preserve.specified will gives you this

```css
:root {--a:b}
body{}
:root{--js:*}
```

**Comment by hgl** [comment]
I thought we agreed that truthy `preserve` preserves definitions?

**Comment by MoOx** [comment]
It just doesn't make sense because we have tests like this


```js
      if (!preserve.specified && !preserve.definitions) {
//...
      if (!preserve.specified || preserve.definitions) {
//...
    if (preserve.specified || preserve.definitions) {
```

So I prefer to get another option to avoid brain mess

```js
      if (!preserve.specified && !preserveDefinitions) {
//...
      if (!preserve.specified || preserveDefinitions) {
//...
    if (preserve.specified || preserveDefinitions) {
```

**Comment by hgl** [comment]
This was what I had in mind

source
```
:root {
  --color: #aaa;
  --color2: var(--color, #bbb);
}
body {
  color: var(--color);
}
```
variables.json
```
{ "foo": "bar"}
```
---

preserve: false
```css
body {
  color: #aaa;
}
```
preserve: "fallback"
```css
:root {
  --color: #aaa;
  --color2: #bbb;
  --color2: #aaa;
  --foo: "bar"
}
body {
  color: #aaa;
}
:root {
  --foo: "bar"
}
```
preserve:"all" | true
```css
:root {
  --color: #aaa;
  --color2: #bbb;
  --color2: #aaa;
}
body {
  color: #aaa;
  color: var(--color);
}
:root {
  --foo: "bar"
}
```
preserve: "computed"
```css
:root {
  --color: #aaa;
  --color2: #aaa;
}
body {
  color: #aaa;
}
:root {
  --foo: "bar"
}
```

**Comment by hgl** [comment]
So you decided to go with object option?

**Comment by hgl** [comment]
When I said i think your four values proposal is pretty good, I mean this:

> false (only new computed values (default))
fallback: fallback (strict behavior) + previous
true || all: specified + previous
"computed-definition": current computed behavior (your hack to be able to extract). Renamed to be clear about what it keep. This option is weird anyway.

Only that "computed-definition" should be "computed".

**Comment by hgl** [comment]
And when I said "And internally, we map the four values for preserve to bools for these variables"

I mean this

```js
var def = false;
var fallback = false;
var specified = false;
var vars = false;
if (preserve === "fallback") {
  def = true;
  fallback = true;
  vars = true;
}
// ..later in resolveValue

if (def) {
  // keep defitions
}
if (fallback) {
  // do fallback
}
// ..etc
```

This is much easier to reason about.

**Comment by MoOx** [comment]
preserving only computed definition is clearly an edge case that require different test everywhere near the "classic" preserve option (cf my previous comment).

The example you give for fallback doesn't make sense. It's useless to keep multiple definitions of the custom prop definitions since browser that will read that would only keep the last value. I don't see any smart use case. 

default behavior of preserve will not add computed values for --* in :root since browser that might read that are supposed to support custom props.

I want simple things, you want the last use case (computed definition) for your extract things. Am I right ?

Let's make things simple. You edge case will be supported but probably as a separate option to avoid making weird things for end user.

**Comment by MoOx** [comment]
"fallback" will just add fallback for normal properties.

**Comment by MoOx** [comment]
Lets consider this

source
```
:root {
  --a: a;
  --b: var(--a, b);
}
body {
  prop: var(--b, c);
}
```
variables
```
{ foo: "bar"}
```
---

preserve: false
```css
body {
  prop: a;
}
```
preserve: "fallback"
```css
body {
  prop: c;
  prop: b;  
  prop: a;
}
```
preserve: true (all)
```css
:root {
  --a: a;
  --b: var(--a, b);
}
body {
  prop: c;
  prop: b;  
  prop: a;
  prop: var(--b, c);
}
```
preserve: "computed"
```css
:root {
  --a: a;
  --b: a;
}
body {
  prop: a;
}
:root {
  --foo: "bar"
}
```
Last use case is completly an edge case since result have nothing to do with previous examples. It's just a simple output which make accessible variables via JS

**Comment by hgl** [comment]
>  It's useless to keep multiple definitions of the custom prop definitions

Didn't think about that. Thanks for the heads up. But if I'm not wrong, the current implementation will add the fallbacks in :root when `preserve: true, strict: true`?

> default behavior of preserve will not add computed values for --* in :root since browser that might read that are supposed to support custom props.

Sounds reasonable.

> You edge case will be supported but probably as a separate option

What's the name for this separate option? How does it work?

**Comment by hgl** [comment]
> Lets consider this

I actually like the example. Yes, `preserve: "computed"` is an edge case, designed specifically for the extract option. How about we make this option undocumented? It's useless other than for the extraction feature.

**Comment by hgl** [comment]
By undocumented, I mean we have the liberty to change the option name. Users are expected to use cssnext to access this feature. They shouldn't use this option directly.

**Comment by MoOx** [comment]
We might add as well

preserve: specified

```css
:root {
  --a: a;
  --b: var(--a, b);
}
body {  
  prop: a;
  prop: var(--b, c);
}
:root {
  --foo: "bar"
}
```
 but it doesn't make much sense to me.

I want to go foward with that plugin by pushing 4.0

Just tell me what are your use case, I don't want to add un required use cases

Here is what I see:

drop strict option
drop appendVariables option (automatic depending on preserve)

preserve: false
(minimal output)
preserve: "fallback"
(safe minimal output)
preserve: true
(future proof output with fallback)
preserve: "computed"
(your edge case)

I will document everything, I don't like undocumented options. We never know what people might want to do with the code you publish.
If we need to change, we can just make a major bump.

Are you ok with that ?

**Comment by hgl** [comment]
Yep, lgtm. We can add `preserve: specified` in the future if a use case pops up.

**Comment by hgl** [comment]
With the default being no fallbacks, no specified values. I now think a better value for "computed" is "definitions"

```
preserve: "definitions" // no fallbacks, no specified values, just definitions
```

**Comment by MoOx** [comment]
After trying to implement that change again, I think we should keep  fallback in a strict option.
So the things we can do is:
- rename and document computed (=> "computed-definitions" to make it clear).
- remove appendVariable and put that automatically for preserve: true or preserve computed definition.
What do you think ?

**Comment by hgl** [comment]
Thank you for continuing working on this.

So the plan is to use two options: strict and preserve?

How do they interact? For example, when preserve is false, how does strict being false/true affect the result?

The whole situation is pretty complex. Let me try to get this straight:

We would like the options to control four things:

1. Whether author's specified variables should be preserved.
2. Whether variables used with a fallback be prepended with a fallback property.
3. Whether author's specified custom-property definitions should be preserved.
4. Whether custom-property definitions specified in js should be appended.

These four are mutually independent. But we would like to introduce options to only allow a subset of all possible combinations, because some of them aren't very useful. 

From our previous discussion, we would like to allow these combinations:

A: min output

1. No
2. No
3. No
4. No

B: max output

1. Yes
2. Yes
3. Yes
4. Yes

C: safe min output

1. No
2. Yes
3. No
4. No

D: output easy to extract custom property definitions

1. No
2. No
3. Yes
4. Yes

Now, how does the two-option strategy map to these four cases?

**Comment by MoOx** [comment]
Hum, this issue starts to give me headache.

The custom definitions scenario is not as simple as you show it, it not just no/no/yes/yes.
3. seems to just be 2. for declarations.

Maybe we are not approching this right way.

Here are some solutions I see (that we can already handle today)
- i want minimal output (min)
- i want minimal safe output (with fallback)
- i want minimal output + my original code (preserve)
- i want minimal safe output + my original code (preserve + fallback)
- i want minimal output + computed definition (preserve: computed).
- i want minimal safe output + computed definition (preserve: computed + fallback).

I think none of them is stupid or weird.

My original idea to simplify this was to provide a unique preserve option in order to use it in cssnext and some other plugins if we can.
In a way I like the way autoprefixer handle at the same time fallback + modern code. I think I would like to end up with the same approch in cssnext, not sure if it's a good idea or a tricky one.
But maybe 2 options (strict + preserve) is better in order to easily control output.

The last scenario is clearly and edge case and I am not considering it in my idea of simplification because it's just something that looks like a hack to me.

**Comment by hgl** [comment]
> Hum, this issue starts to give me headache.

Yes, it's taking longer than it should. 

> it not just no/no/yes/yes.

Mind to elaborate on what's missing? 

> 3. seems to just be 2. for declarations.

Not quite understand it. Do you mean `#3` and `#2` are the same for properties in `:root {...}`?

> Here are some solutions I see (that we can already handle today)

I see where you are coming from with the two options. They actually maps to these combinations of the four conditions:

- i want minimal output (min)
  no/no/no/no

- i want minimal safe output (with fallback)
  no/yes/no/no

- i want minimal output + my original code (preserve)
  yes/no/yes/yes

- i want minimal safe output + my original code (preserve + fallback)
  yes/yes/yes/yes

The last two scenarios:

- i want minimal output + computed definition (preserve: computed).
  no/no/yes/yes

- i want minimal safe output + computed definition (preserve: computed + fallback).
  no/yes/yes/yes

I think we should just define five keywords in one option to map to the five scenario (the last scenario isn't very useful like you said). Because as you can see the two-option way breaks down when we need to add one more scenario. With two options, one option takes three values (true, false, computed) and the other take take two (true, false), you are forced to deal with six possible combinations, even if you are only interested in five.

**Comment by MoOx** [comment]
I think it's not a good idea to handle several options under flag. What if a some new scenarios came up ?

**Comment by MoOx** [comment]
>  you are forced to deal with six possible combinations, even if you are only interested in five.

And what is the problem with that ?

**Comment by hgl** [comment]
> What if a some new scenarios came up ?

If a new scenario comes up, either it is independent of existing scenarios, in which case we simply add a new keyword to the sole option, with existing keywords having the effect of disabling this new scenario. Or, if it affects existing scenarios, we have to introduce a breaking change to modify the behavior of existing keywords. Note that if we use two options approach, we still have to make this breaking change, adding a new option won't be enough, because it affects existing scenarios even if it's false.

> And what is the problem with that ?

Like you previous mentioned. You have to explain to users some particular option combinations are ignored. With one option approach, there is nothing to explain, users simply use one of the keywords we introduced and that's it.

**Comment by MoOx** [comment]
Do you have lot's of example of this kind of string options that handle multiple scenarios ? Doesn't seems like a good pattern.

**Comment by hgl** [comment]
Think this option like a screen color profile:

![screen shot 2015-04-27 at 3 01 40 pm](https://cloud.githubusercontent.com/assets/7038035/7342993/54b34f0a-ecee-11e4-9e49-72530249f83f.png)

What changing the profile really does is to change the underlying options. The profile merely contains the combination of these options.

What we are doing is to allow the user to change the profile, but not the underlying options.

Hope that makes sense.

**Comment by hgl** [comment]
Actually autoprefixer also provides this kind of option.

What `Firefox < 20` really does is `['Firefox 19', 'Firefox 18', ...]`.

**Comment by MoOx** [comment]
You example doesn't reflect our situation. 
Color profile can be calibrated by hand, and autoprefixer browsers option is to define a range & provide a very wife range of possibility.

**Comment by hgl** [comment]
> Color profile can be calibrated by hand

That's why I said "what we are doing is to allow the user to change the profile, but not the underlying options."

> autoprefixer browsers option is to define a range

The point is it allows users to specify a string, which enables a couple of sub-options. This is what I'm suggesting us to do.

To give one more example, think photoshop brushes. When you select a brush preset, what you really did is to apply the sub-option it contains (brush size, roundness, hardness). The keywords we are going to define is like brush presets. To prevent users from generating ugly brushes, we disallow them to change the sub-options individually, only selecting brush presets that we defined is allowed.

**Comment by MoOx** [comment]
You example with brush is wrong from what I know of photoshop. Brush are defined by some pictures that you can apply some transformations on.

**Comment by hgl** [comment]
> Brush are defined by some pictures that you can apply some transformations on.

That's one of its sub-option called texture.

See the sub-options it provides:
![screen shot 2015-04-29 at 2 27 32 pm](https://cloud.githubusercontent.com/assets/7038035/7385631/0aa2c654-ee7c-11e4-9285-82879a68a699.png)

OK, to give some js example, see babel's transformers: https://babeljs.io/docs/usage/transformers/

We can define four options to give users total control over the final output, just like babel exposing all its transformers.

Only that we decided some of the options combinations don't make sense. So we define keywords to controls these four options. Babel, actually already contains such keywords. See the es6, es7 prefixes? Babel could in principle define a single options accepting es6 or es7 to enable corresponding transformers at once.

**Comment by hgl** [comment]
I think three keywords might be enough:

preserve: false // I want minimal output that works
preserve: 'all' // I want spec compliant output
preserve: 'definitions' // I want to extract custom properties definitions

I'm unable to come up with a compelling use case for enabling fallback but not keep `:root {...}` for example. Too many options might confuse users.

**Comment by MoOx** [comment]
That's what I realize when I started working on this.
So I think we should have strict option for fallback and preserve (false, true "computed-definition").
Sorry for insisting on "computed-definitions" but I really think it's more clear than just "computed" or just "definitions".
Does this looks good to you ?

**Comment by hgl** [comment]
Sure, `computed-definitions` is fine.

**Comment by MoOx** [comment]
I think I will revert this, since we only talking about edge cases.
I will keep fallback by default since I don't want to introduce differences with the specs & leave options as they are for now. Not a big deal imo since nobody came here and ask for news.

For strict, default to false, so no major bump. If you use many fallbacks & want a small output, you will be able to use the strict: false options.

Other options are edge cases anyway.

**Comment by hgl** [comment]
After all this time, I actually forgot what all these options do.  Have to try pretty hard to remember again what they do and how some options don't have effect when some other options are on/off. No to mention people that are not familiar with this plugin.

If you are willing to accept variable extraction in cssnext then I don't think option to preserve computed definitions is an edge case, and I think the current "multiple options to control the output" design is a total mess.

But I guess not many people with fight with options in this plugin, they will simply use cssnext, and this discussion is taking longer than it should. So I'm not willing to fight it out.

I'm eager to send the extract PR to cssnext once all options are stable, my fork seems to lag behind your branch pretty significantly already.

**Comment by MoOx** [comment]
Since nobody ask for that for a while. We might reconsider this later.
