### ISSUE TITLE
options in postcss json file

### ISSUE THREAD

**Issue by Frikki** [postcss/postcss-custom-properties#40]
How do you specify the options in a postcss json file? I’ve tried

```json
{
  "use": [
    "postcss-import",
    "postcss-custom-properties",
    "postcss-cssnext"
  ],
  "postcss-custom-properties": {
    "warnings": false
  },
  "postcss-cssnext": {
    "browsers": [
      "ie >= 10",
      "ie_mob >= 10",
      "ff >= 30",
      "chrome >= 34",
      "safari >= 7",
      "opera >= 23",
      "ios >= 7",
      "android >= 4.4",
      "bb >= 10"
    ]
  }
}
```

...but it still outputs warnings when custom properties are not scoped to :root element.

**Comment by MoOx** [comment]
where did you see that it's doable?

**Comment by Frikki** [comment]
Here https://github.com/postcss/postcss-custom-properties#warnings

**Comment by MoOx** [comment]
I talk about the json thing.
Anyway, if you use postcss-cssnext, you need to pass option to this plugin by postcss-cssnext features options.

**Comment by Frikki** [comment]
Well, I thought that was what I was doing above. I use a config file that specifies the feature options for postcss-cssnext. But if this cannot be done, then... well.

**Comment by MoOx** [comment]
This can be done via this option http://cssnext.io/usage/#features (that works in postcss-cssnext)

**Comment by Frikki** [comment]
Ah, thanks for clearing this up.
