### ISSUE TITLE
Discussion: preserve: withFallbacks

### ISSUE THREAD

**Issue by kevinSuttle** [postcss/postcss-custom-properties#48]
https://github.com/postcss/postcss-custom-properties#preserve

Would it be beneficial to add a `withFallbacks` value to the `preserve` property, where the Custom Property is both replaced and added?

e.g. 
Authored:
```css
color: var(--HighlightGreen)
```

Compiled
```css
color: #3acfb6
color: var(--HighlightGreen)
```

This is mostly for debug purposes, I suppose, but it could be a nice addition, IMO.

**Comment by MoOx** [comment]
preserve option should already do that: keep the original value in addition to the generated value.

**Comment by kevinSuttle** [comment]
Thanks!

**Comment by kevinSuttle** [comment]
Doesn't seem to be working as of 5.0.1.

<img width="526" alt="screen shot 2016-08-23 at 11 32 52 am" src="https://cloud.githubusercontent.com/assets/95672/17898349/6f31a1f6-6925-11e6-8173-cfe2e0f3750e.png">

My config: 
```js
postcss: function () {
      return [
        require('postcss-import')({
          addDependencyTo: webpack,
        }),
        customProperties({
          preserve: true,
          variables: kratosVars,
          appendVariables: true,
        }),
        cssApply,
        autoprefixer,
      ]
    },
```

**Comment by kevinSuttle** [comment]
Since removed the vars, and still the same behavior. Even with a different webpack config.
```js
  postcss: function () {
      return [
        atImport(),
        customProperties({ preserve: true }),
        cssApply(),
        autoprefixer(),
      ]
    },
```

**Comment by MoOx** [comment]
The best thing you can do to help as I don't have much time, is to try to make a PR to this repo that reproduce the issue.

**Comment by kevinSuttle** [comment]
It appears to be something else, but I can't confirm what. Will post more details if it happens again. Thanks, @moox.
