### ISSUE TITLE
Limited to one file? 

### ISSUE THREAD

**Issue by kevinSuttle** [postcss/postcss-custom-properties#50]
In my experience, it's only possible to have one `:root` declaration, and that usually means one file (doesn't seem to work with postcss-imports). Am I missing something?

**Comment by MoOx** [comment]
This is totally wrong, you can have as much :root as you want. You can try in http://cssnext.io/playground/ for example.
Lot's of libraries like cssrecipes use multiples declarations and work fine.

**Comment by kevinSuttle** [comment]
Thanks for confirming, @MoOx.

**Comment by tomasdev** [comment]
if you do it via @import it ends up triggering a warning, ` postcss-custom-properties: /Users/.../src/style/index.css:14:5: variable '--gvar' is undefined and used without a fallback` even though output works
