### ISSUE TITLE
Add JS variables to generated CSS :root

### ISSUE THREAD

**Issue by jiayihu** [postcss/postcss-custom-properties#60]
I'm currently using this plugin in an Angular 2 project, where `.css` files are local to their components and separated between each other.
The `variables` configuration option comes very handy for this situation and I was wondering about the possibility of adding them to `:root` if `preserve` option is `true` and a css file path is specified, for instance `./src/styles/main.css`.

**Comment by MoOx** [comment]
Not sure it makes sense here, I guess you can handle that yourself very easily.

**Comment by sshmyg** [comment]
Is it expected behaviour when `preserve: true`, than param `variables` doesn't work? I mean css bundle has no `:root` with vars from configuration.
Config
```javascript
'postcss-cssnext': {
            browsers: ['last 2 versions'],
            features: {
                customProperties: {
                    preserve: true,
                    variables: {
                        'bg-color': 'red'
                    }
                }
            }
        }
``` 

CSS bundle (no `:root`)
```css
body {
    background-color: var(--color-bg);
}
```

**Comment by jiayihu** [comment]
IIRC the `preserve` option will mantain the custom properties at runtime where you ease them but it does not add them. For that you must use or write another postcss plugin.

**Comment by jonathantneal** [comment]
Sorry for not closing this earlier. @jiayihu answered this a year ago.
