### ISSUE TITLE
When `custom-property-name` same as `property-name`

### ISSUE THREAD

**Issue by helloyou2012** [postcss/postcss-custom-properties#61]
I want to override property like this:

```
:root {
  --main-color: #333;
  --main-color: var(--main-color, #666);
}
h1 {
  color: var(--main-color);
}
```

Current output is

```
h1 {
  color: #666;
}
```

But I expect

```
h1 {
  color: #333;
}
```

**Comment by MoOx** [comment]
You cannot "override" a property using itself. You are not in a programming language. It's how the spec works sorry. (Try in a browser that support custom props like Firefox or latest Chrome)

**Comment by helloyou2012** [comment]
@MoOx thanks, but so pity. I have just leave a issue https://github.com/w3c/csswg-drafts/issues/876
