### ISSUE TITLE
Custom properties strips !important semicolon

### ISSUE THREAD

**Issue by oleersoy** [postcss/postcss-custom-properties#62]
Reproduce steps:
``` console
git clone git@github.com:superfly-css/superfly-css-utilities-colors.git
cd superfly-css-utilities-colors
npm install
gulp build:css
cat target/main/css/index.css
```

The `;` is removed from the `!important;` markup in the `src/main/css/index.css` file.  

If the `postcss-custom-properties` processor is removed from the list of processors, then the semicolon stays intact.  To do this delete the `postcss-custom-properties` processor from the array of processors like this:

``` console
atom node_modules/superfly-css-task-build/src/main/js/index.js 
```
After deletion the list of processors looks like this:
``` js
var processors = [postcss_import, postcss_each, postcss_calc, postcss_color_function, autoprefixer, postcss_reporter({
  clearMessages: true
})];
```
Run:
``` console
gulp clean
gulp build:css
cat target/main/css/index.css
```

The semicolon is now included in the output.

**Comment by MoOx** [comment]
1) A trailing semicolon is optional in CSS
2) the responsible of this is maybe postcss api since we clone a value before replacing the actual value, so maybe open an issue over there.
