### ISSUE TITLE
Can't Modify Tests

### ISSUE THREAD

**Issue by oleersoy** [postcss/postcss-custom-properties#64]
[SO Summary Here](http://stackoverflow.com/questions/42286782/javascript-without-semicolons)

**Comment by MoOx** [comment]
Please take 10sec to add proper description here.

**Comment by oleersoy** [comment]
If I place a comment like `/* Any Comment */` at the top of `test/index.js` I get the following output when running the test:
``` console
   20:30  error  Missing trailing comma  comma-dangle
   91:22  error  Missing trailing comma  comma-dangle
   150:30  error  Missing trailing comma  comma-dangle
   193:19  error  Missing trailing comma  comma-dangle
   200:25  error  Missing trailing comma  comma-dangle

   ✖ 5 problems (5 errors, 0 warnings)
```

**Comment by MoOx** [comment]
Sorry I cannot reproduce. Looks like your IDE is removing some trailing comma when you save a file, that might be causing the issue.

**Comment by oleersoy** [comment]
Wow - OK - Was using Atom for editing and you are right - it's causing it.  Tried it in VI and no problemo.  Just when I was starting to love Atom ...

**Comment by MoOx** [comment]
This is definitely coming from a plugin. I use atom without issue.

**Comment by oleersoy** [comment]
Yeah it's probably beautify or something.  Theres a similar issue documented here:
https://github.com/Glavin001/atom-beautify/issues/534

I asked how to track it down here:
http://stackoverflow.com/questions/42301411/how-to-detect-which-plugin-performs-an-action-on-save-in-atom

Meanwhile I'll just edit in VI.  Hope to have https://github.com/postcss/postcss-custom-properties/issues/63 worked out soon.
