### ISSUE TITLE
Variables defined in imported CSS are not found

### ISSUE THREAD

**Issue by jdolle** [postcss/postcss-custom-properties#68]
Without inlining imports, variables defined in another file then `@import`ed are considered undefined.

I want to use css-loader's modules, `@import` a file that defines my variables, then use those variables in a variety of modules. Currently my compiled css is correct, but I see warnings for my variables `___ is undefined and used without a fallback`.

**Comment by MoOx** [comment]
Sorry no magic possible. This module won't process import and duplicate the job done by postcss-import.
