### ISSUE TITLE
Interpolation

### ISSUE THREAD

**Issue by trisys3** [postcss/postcss-custom-properties#72]
Is it possible in the spec to use variables in string interpolation? If not, is there a way to add it here, and is that appropriate? Otherwise I suppose I could use `postcss-simple-vars`, but I wanted to be more future-compatible.

For example (directly from [the LESS site](http://lesscss.org/features/#variables-feature-variable-interpolation)):

> ```
> // Variables
> @my-selector: banner;
> 
> // Usage
> .@{my-selector} {
 >    font-weight: bold;
  >   line-height: 40px;
  >   margin: 0 auto;
> }
> ```
> 
> Compiles to:
> 
> ```
> .banner {
>     font-weight: bold;
>     line-height: 40px;
>     margin: 0 auto;
> }
> ```

**Comment by tohuw** [comment]
@trisys3, why not use [custom selectors](http://cssnext.io/features/#custom-selectors) for this case?

**Comment by trisys3** [comment]
That makes sense. Is it possible to do variable interpolation where the variable is not the whole selector? I can't tell from the plugin documentation.

**Comment by tohuw** [comment]
@trisys3 Possibly not. See my issue #79 which may be exemplifying this.

**Comment by tohuw** [comment]
(Ignore the comment I deleted, I misread what you typed)

You mean you want a selector for e.g. `.banner-top` such that you can write:

    @custom-selector :--banner .banner
    
    /* N.B.: PSEUDOCODE */
    {:--banner}-top

I don't see that anywhere in the underlying spec, and I'd be surprised if it was planned. Why not use multiple class names in the instances like this, or some principle like BEM?

**Comment by trisys3** [comment]
You're probably right, we could use something like that. We have something in LESS already, but I am going to need to refactor that code anyway. It would still be nice to have something like this, but it looks like CSS is going to stay really minimal in cases like this, which is fair.

You can close this if you want.

**Comment by jonathantneal** [comment]
Sorry it took so long to close this. 😸
