### ISSUE TITLE
use with postcss-mixins

### ISSUE THREAD

**Issue by Memoyr** [postcss/postcss-custom-properties#83]
Hi , 
Is it normal that this isn't working while using with postcss-mixins ? It strips out everything from the rule value but not the actual argument. 

```
@define-mixin generate $size {
    font-size: var(--text$(size);
}
.test {
  @mixin generate sm;
}
```

**output :** 

.test {
font-size: sm;
}

thanks

**Comment by Semigradsky** [comment]
Use `postcss-mixins` before `postcss-custom-properties`

**Comment by Memoyr** [comment]
thanks! 
Actually, that was the correct fix for my config : 
https://github.com/postcss/postcss-mixins/issues/82#issuecomment-355792125
