### ISSUE TITLE
Breaking change in 6.3.0 (preserve: true)

### ISSUE THREAD

**Issue by rexxars** [postcss/postcss-custom-properties#93]
Hi,

6.3.0 switched to `preserve: true` by default, which breaks a whole lot of things for us. Shouldn't this be a major release signaling a breaking change?

I'd be super happy if a patch/minor could be released that reverted the change, and rather change the default in 7.0.0.

Thoughts?

**Comment by vikshv** [comment]
+1

**Comment by jonathantneal** [comment]
I’m okay with this, but I’m curious — shouldn’t `preserve` also include the fallback values for unsupported browsers? How are you using Custom Properties?

**Comment by rexxars** [comment]
I don't have a full picture of the problem, but I suspect the problem lies with combining it with `postcss-import`. Either way, since it can interfere with CSS variables set in other parts of the application, it shouldn't be introduced in a minor version.

**Comment by jonathantneal** [comment]
It suspect it interferes when Custom Properties are not used to spec. I’ve published 6.3.1 which reverts the option changes in 6.3.0 that will be restored in 7.0.0.

**Comment by rexxars** [comment]
Thanks a bunch ❤️

**Comment by jonathantneal** [comment]
Thank you for reporting the issue. I’m keeping this issue open until you’ve confirmed that everything is back to working as expected.

**Comment by jonathantneal** [comment]
@rexxars, are things back to normal?

**Comment by rexxars** [comment]
Yup! Thanks again.
